/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-container": "#fc7c78",
        "background": "#f4fbf4",
        "surface-tint": "#006c49",
        "surface-container": "#e8f0e9",
        "secondary-fixed": "#e1e2e4",
        "inverse-primary": "#4edea3",
        "primary-container": "#10b981",
        "secondary-fixed-dim": "#c5c6c8",
        "primary": "#006c49",
        "surface-bright": "#f4fbf4",
        "tertiary": "#a43a3a",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eef6ee",
        "surface-container-high": "#e3eae3",
        "on-primary-fixed-variant": "#005236",
        "on-error-container": "#93000a",
        "outline-variant": "#bbcabf",
        "on-secondary-fixed-variant": "#444749",
        "on-tertiary-fixed-variant": "#842225",
        "inverse-on-surface": "#ebf3eb",
        "on-primary": "#ffffff",
        "outline": "#6c7a71",
        "surface": "#f4fbf4",
        "on-surface-variant": "#3c4a42",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdad7",
        "surface-dim": "#d4dcd5",
        "on-background": "#161d19",
        "on-secondary-fixed": "#191c1e",
        "surface-container-highest": "#dde4dd",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#606365",
        "secondary-container": "#dee0e2",
        "on-surface": "#161d19",
        "primary-fixed-dim": "#4edea3",
        "on-error": "#ffffff",
        "on-primary-fixed": "#002113",
        "surface-variant": "#dde4dd",
        "secondary": "#5c5f60",
        "inverse-surface": "#2b322d",
        "on-tertiary-fixed": "#410005",
        "tertiary-fixed-dim": "#ffb3af",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "on-tertiary-container": "#711419"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "container-padding": "3rem",
        "card-gap": "1.5rem",
        "stack-sm": "0.5rem",
        "section-gap": "4rem"
      },
      fontFamily: {
        "headline-lg": ["Inter", "Geist", "sans-serif"],
        "label-lg": ["Inter", "Geist", "sans-serif"],
        "display": ["Inter", "Geist", "sans-serif"],
        "body-lg": ["Inter", "Geist", "sans-serif"],
        "headline-sm": ["Inter", "Geist", "sans-serif"],
        "label-md": ["Inter", "Geist", "sans-serif"],
        "headline-lg-mobile": ["Inter", "Geist", "sans-serif"],
        "body-md": ["Inter", "Geist", "sans-serif"],
        "headline-md": ["Inter", "Geist", "sans-serif"],
        "geist": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
